### ISSUE TITLE
support for rollup bundler

### ISSUE THREAD

**Issue by davelandry** [juliangruber/tape-run#35]
I've been experimenting using [rollup](https://github.com/rollup/rollup) to bundle my code instead of browserify, but I can't get it working with tape-run! Has anyone else tried this?

**Comment by juliangruber** [comment]
can you post what you did to try out?

**Comment by davelandry** [comment]
I created a stripped down environment for my test. Here's what needs to be installed:
```sh
npm install rollup rollup-plugin-babel rollup-plugin-commonjs rollup-plugin-node-resolve babel-preset-es2015-rollup tape tape-run
```

Here's my sample test file, `test.js`:
```js
import {test} from "tape";

test("true", (assert) => {
  assert.true(true);
  assert.end();
});
```

Here's the configuration for rollup, saved as `rollup.config.js`:
```js
import babel from "rollup-plugin-babel";
import commonjs from 'rollup-plugin-commonjs';
import deps from "rollup-plugin-node-resolve";

export default {
  dest: "build.js",
  entry: "test.js",
  format: "umd",
  plugins: [
    commonjs(),
    deps({"jsnext": true, "main": true}),
    babel({"presets": ["es2015-rollup"]})
  ]
};
```

And finally, the script used to run everything:
```sh
rollup -c && cat build.js | tape-run | faucet
```

I get the following error:
```sh
TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at http://localhost:59554/bundle.js:7:45
    at http://localhost:59554/bundle.js:4:20
    at http://localhost:59554/bundle.js:5:2
```

**Comment by juliangruber** [comment]
Does this work? `cat build.js | node`

**Comment by davelandry** [comment]
Good call, doesn't work. I get this error:
```bash
TypeError: inherits is not a function
```
Seems like an error with my bundler, probably the plugins.

**Comment by Thomasvdam** [comment]
Did you ever get this to work? I'm trying this out at the moment but I keep getting issues with bundling my test file. I use the following build config (which I got to after some trial and error with the excludes), but now it won't require 'fs' properly and this breaks the output. Any tips would be appreciated. :)

```JavaScript
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';
import builtins from 'rollup-plugin-node-builtins';

export default {
    dest: 'test.bundled.js',
    entry: 'test/test.js',
    format: 'umd',
    moduleName: 'testModule',
    plugins: [
        builtins(),
        nodeResolve({
            jsnext: true,
            browser: true,
            preferBuiltins: false,
        }),
        commonjs({
            exclude: ['node_modules/rollup-plugin-node-globals/**'],
        }),
        babel({
            presets: ['es2015-rollup'],
            exclude: ['./node_modules/**/*'],
            babelrc: false,
        }),
    ],
};
```

**Comment by davelandry** [comment]
@thomasvdan unfortunately no, every time I feel like I get past one error message another pops up. Have tried both through CLI and JavaScript APIs in a Node environment.

**Comment by Thomasvdam** [comment]
@davelandry I managed to get a bundle to run through node and tape-run with a lot of hacking, but maybe someone smarter than me can figure out what is going wrong in the build process.

First off mangled Tape by changing [this](https://github.com/substack/tape/blob/master/lib/default_stream.js#L2) line to `var fs = {}`, which makes the bundle compile albeit with a some complaints about cyclical dependencies:

```
Module commonjs-proxy:/.../node_modules/readable-stream/lib/_stream_duplex.js may be unable to evaluate without /.../node_modules/readable-stream/lib/_stream_duplex.js, but is included first due to a cyclical dependency. Consider swapping the import statements in /.../test/test.js to ensure correct ordering
Module commonjs-proxy:/.../node_modules/readablestream/lib/_stream_readable.js may be unable to evaluate without /.../node_modules/readable-stream/lib/_stream_readable.js, but is included first due to a cyclical dependency. Consider swapping the import statements in /.../test/test.js to ensure correct ordering
```
As expected this throws an error when piping it into node:
```
[stdin]:330
    ctor.prototype = Object.create(superCtor.prototype, {
                                            ^

TypeError: Cannot read property 'prototype' of undefined
    rest of stacktrace here.
```

This is what the dependency warning is about, it is attempting to create the Duplex class and make it inherit from Readable while Readable hasn't been defined yet. To solve this I hoisted the initialisation for Readable to be just above the Duplex initialisation which got the tests to pass in node, yay!

But, it still wasn't working in tape-run, due to the numerous uses of `process` and in particular `process.nextTick`. I added `window.process = {};` to the top of the file and replaced every instance of `process.nextTick` with a `timeout` (may also have been a few more replacements of variants of the `process.nextTick` but that find/replace will get you far). All this combined got me a running test in tape-run:
```
cat test.bundled.js | ./node_modules/.bin/tape-run
TAP version 13
# Dummy test
ok 1 should be equal
ok 2 should not be equal

1..2
# tests 2
# pass  2

# ok
``` 

Sorry for the wall of text but I hope that this might help someone in tracking down the real issue here.

**Comment by lorenzofox3** [comment]
I have created [zora](https://github.com/lorenzofox3/zora) with that in mind (no dependency to core node modules) which I use instead of tape and I have not bumped into any error so far

**Comment by juliangruber** [comment]
awesome!

**Comment by juliangruber** [comment]
we have a webpack plugin now! https://github.com/juliangruber/tape-run/commit/e6ea66cebd093d8e2a6b817f488b73514bce7e12

**Comment by fregante** [comment]
Closing as probably obsolete by now. Rollup has changed a lot since
